apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-db
  labels:
    app: pg-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-db
  template:
    metadata:
      labels:
        app: pg-db
    spec:
      containers:
      - name: pg-db
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "posts"
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  selector:
    app: pg-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432